language: node_js
services:
  - docker
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy
  - docker tag udagram-api-feed msh7olak/udagram-api-feed:v1
  - docker tag udagram-api-user msh7olak/udagram-api-user:v1
  - docker tag udagram-frontend msh7olak/udagram-frontend:v1
  - docker tag reverseproxy msh7olak/reverseproxy:v1
  #!/bin/bash
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push msh7olak/udagram-api-feed:v1
  - docker push msh7olak/udagram-api-user:v1
  - docker push msh7olak/udagram-frontend:v1
  - docker push msh7olak/reverseproxy:v1





