apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector: 
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
        api: external        
    spec:
      containers:
      - name: frontend
        image: msh7olak/udagram-frontend:v2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
